In [5]:
pwd()

'/home/emmanuel/ML'

In [2]:
ls

 Volume in drive C is OS
 Volume Serial Number is 7678-0726

 Directory of C:\Users\dauxu\Desktop\ex3_hoai

11/15/2019  12:32 PM    <DIR>          .
11/15/2019  12:32 PM    <DIR>          ..
11/15/2019  10:01 AM    <DIR>          .ipynb_checkpoints
11/15/2019  09:26 AM           105,591 linear1.pdf
11/15/2019  09:31 AM             9,925 LinearAlgebra_Data.xlsx
11/15/2019  12:01 PM             9,679 LinearAlgebra_Data_solu.xlsx
11/15/2019  12:32 PM             6,348 Untitled.ipynb
               4 File(s)        131,543 bytes
               3 Dir(s)  63,717,347,328 bytes free


In [6]:
import pandas as pd
import numpy as np

In [7]:
f = pd.read_excel('LinearAlgebra_Data.xlsx',headers=0)

In [8]:
f.head(3)

Driver ID  A (g/l)  S (km/h)  D (m)
0          1     0.10       101     79
1          2     0.07        90     65
2          3     0.61        94     97

In [9]:
A= f.iloc[:,1:3]
A.head(3)

A (g/l)  S (km/h)
0     0.10       101
1     0.07        90
2     0.61        94

In [10]:
A = A.values

In [11]:
A.shape

(50, 2)

In [12]:
# display 3 row of A : this matrix contain(A, S)
A[:3,:]

array([[1.00e-01, 1.01e+02],
       [7.00e-02, 9.00e+01],
       [6.10e-01, 9.40e+01]])

In [13]:
# add column all values = 1, thêm cột giá trị bằng 1 vào phía trước của A, this matrix contain(u, A, S) with u = ones(50,1)
# u là vector =1 dim = 50
A =np.append(np.ones([50,1]),A, axis=1)
A[0:3,:]


array([[1.00e+00, 1.00e-01, 1.01e+02],
       [1.00e+00, 7.00e-02, 9.00e+01],
       [1.00e+00, 6.10e-01, 9.40e+01]])

In [14]:
A.shape

(50, 3)

#### exo 2.2.a => xem note của em, chỗ hình chiếu ||v-vo|| = min||v-u|| with u in F,  (|v-u|  + |u-vo|)^2 >= |v-vo|^2

#### exo  2.2.b => compute orthorgonal projection = solve new system which is A.T * A * lambda = A.T * D ( trong note luon)

In [15]:
# A.T * A (3,50)*(50,3) =(3,3)
left = np.dot(A.T, A)
left.shape

(3, 3)

In [18]:
# A.T * D (3,50)*(50,1) = (3,1)
D = f.iloc[:, 3:4].values
right = np.dot(A.T,D)
right.shape

(3, 1)

In [46]:
left

array([[5.0000e+01, 1.4550e+01, 4.4680e+03],
       [1.4550e+01, 5.9361e+00, 1.2954e+03],
       [4.4680e+03, 1.2954e+03, 4.0300e+05]])

In [47]:
right

array([  3604.  ,   1123.51, 326853.  ])

In [55]:
# lamda0, 1, 2 can be computed = inv(A.T*A)*(A.T*D) = inv(left)*right
lamda = np.dot(np.linalg.inv(left),right)
lamda

array([-61.94813152,  47.69757633,   1.34454047])

#### exo 2.2.c compute MSE of this model

In [56]:
# = (D - lamda*A)^2

In [66]:
D_ = np.dot(A,lamda)
D_

array([ 78.62021405,  62.39934153,  93.53419465,  79.48777876,
        44.87527368,  65.08842248,  67.46960474,  62.91766243,
        75.49550246,  94.83739   ,  68.25078264,  88.02830081,
        72.50591594,  62.13648453,  69.29112098,  75.66827609,
        90.32679281,  96.39604923,  74.84205651,  59.14689801,
        62.8763173 ,  63.30825137,  48.64973466,  75.40911565,
        86.94292078,  59.01546951,  58.71126737,  61.87732408,
        67.77380688,  70.24507251,  85.68846368,  64.08942927,
        59.87933766,  73.62894454,  91.8891486 , 103.33287036,
        95.66360958,  64.9119523 ,  59.27462995,  64.60775016,
        81.00509286,  75.14625864,  99.38933231,  50.42620921,
        62.44068666,  72.46087425,  47.86855676,  55.02688977,
        77.23063188,  83.91198913])

In [19]:
D

array([[ 79],
       [ 65],
       [ 97],
       [ 81],
       [ 46],
       [ 67],
       [ 78],
       [ 58],
       [ 69],
       [107],
       [ 57],
       [101],
       [ 78],
       [ 56],
       [ 79],
       [ 66],
       [103],
       [ 97],
       [ 82],
       [ 64],
       [ 66],
       [ 60],
       [ 52],
       [ 71],
       [ 94],
       [ 60],
       [ 58],
       [ 59],
       [ 57],
       [ 79],
       [ 81],
       [ 62],
       [ 69],
       [ 62],
       [ 80],
       [ 92],
       [ 88],
       [ 57],
       [ 57],
       [ 55],
       [ 79],
       [ 85],
       [102],
       [ 48],
       [ 59],
       [ 72],
       [ 50],
       [ 62],
       [ 72],
       [ 86]])

In [72]:
MSE = np.sum((D-d_)**2)
MSE

2385.274279516432